// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrendService.DBContext;

#nullable disable

namespace TrendService.Migrations
{
    [DbContext(typeof(TrendDbContext))]
    [Migration("20260609131712_InitTrendDb")]
    partial class InitTrendDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrendService.Models.JournalTrendSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("CitationSum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("citation_sum");

                    b.Property<double?>("GrowthRate")
                        .HasColumnType("double precision")
                        .HasColumnName("growth_rate");

                    b.Property<Guid>("JournalId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_id");

                    b.Property<string>("JournalName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("journal_name");

                    b.Property<int>("PaperCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("paper_count");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("journal_trend_snapshots_pkey");

                    b.HasIndex(new[] { "JournalId" }, "idx_journal_trend_id");

                    b.HasIndex(new[] { "Year" }, "idx_journal_trend_yr");

                    b.HasIndex(new[] { "JournalId", "Year" }, "uq_journal_trend")
                        .IsUnique();

                    b.ToTable("journal_trend_snapshots", (string)null);
                });

            modelBuilder.Entity("TrendService.Models.ReportCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ParamsHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("params_hash");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("report_type");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json");

                    b.HasKey("Id")
                        .HasName("report_cache_pkey");

                    b.HasIndex(new[] { "ExpiresAt" }, "idx_report_expires");

                    b.HasIndex(new[] { "ReportType", "ParamsHash" }, "idx_report_lookup");

                    b.HasIndex(new[] { "ReportType", "ParamsHash" }, "uq_report_cache")
                        .IsUnique();

                    b.ToTable("report_cache", (string)null);
                });

            modelBuilder.Entity("TrendService.Models.SearchHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("query");

                    b.Property<int?>("ResultCount")
                        .HasColumnType("integer")
                        .HasColumnName("result_count");

                    b.Property<string>("SearchType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("search_type");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("search_history_pkey");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_search_created")
                        .IsDescending();

                    b.HasIndex(new[] { "UserId" }, "idx_search_user");

                    b.ToTable("search_history", (string)null);
                });

            modelBuilder.Entity("TrendService.Models.TrendSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("CitationSum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("citation_sum");

                    b.Property<double?>("GrowthRate")
                        .HasColumnType("double precision")
                        .HasColumnName("growth_rate");

                    b.Property<Guid>("KeywordId")
                        .HasColumnType("uuid")
                        .HasColumnName("keyword_id");

                    b.Property<string>("KeywordTerm")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("keyword_term");

                    b.Property<int>("PaperCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("paper_count");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("trend_snapshots_pkey");

                    b.HasIndex(new[] { "KeywordId" }, "idx_trend_kw_id");

                    b.HasIndex(new[] { "KeywordTerm" }, "idx_trend_kw_term");

                    b.HasIndex(new[] { "Year" }, "idx_trend_year");

                    b.HasIndex(new[] { "KeywordId", "Year" }, "uq_keyword_trend")
                        .IsUnique();

                    b.ToTable("trend_snapshots", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
